# Generated by Django 3.0.4 on 2020-03-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000)),
                ('author', models.CharField(default='', max_length=1000)),
                ('labels', models.CharField(default='', max_length=1000)),
                ('description', models.TextField(default='')),
                ('image_link', models.CharField(default='', max_length=1000)),
                ('image_height', models.IntegerField(default=200)),
                ('reviews', models.TextField(default='')),
            ],
        ),
    ]
