# Generated by Django 3.0.4 on 2020-03-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200321_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_width',
            field=models.IntegerField(default=200),
        ),
    ]
